#!/usr/bin/env python3
"""Assemble the static site in docs/ from post JSON files in data/posts/.

Each post file: { slug, title, repo, repo_url, date, summary, explainer_url,
body_html, stars, language }
body_html is trusted (generated by our own pipeline).
"""
import glob
import hashlib
import html
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DOCS = os.path.join(ROOT, "docs")
SITE_NAME = "Repo, Explained"
TAGLINE = "One trending GitHub repo, explained visually. Every day. Fully automated."

PAGE = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title}</title>
<meta name="description" content="{description}">
<link rel="stylesheet" href="{base}style.css?v={cssv}">
<link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>📦</text></svg>">
</head>
<body>
<header>
  <a class="brand" href="{base}index.html">📦 {site}</a>
  <p class="tagline">{tagline}</p>
</header>
<main>
{content}
</main>
<footer>
  <!-- AD SLOT: paste your EthicalAds / Carbon snippet here -->
  <p>Generated automatically with Claude Code + Scrimba Explain.</p>
</footer>
</body>
</html>
"""


def load_posts():
    posts = []
    for path in glob.glob(os.path.join(ROOT, "data", "posts", "*.json")):
        with open(path) as f:
            posts.append(json.load(f))
    posts.sort(key=lambda p: p["date"], reverse=True)
    return posts


def esc(s):
    return html.escape(s or "", quote=True)


def css_version():
    with open(os.path.join(DOCS, "style.css"), "rb") as f:
        return hashlib.sha1(f.read()).hexdigest()[:8]


def render_index(posts):
    cards = []
    for p in posts:
        cards.append(f"""<article class="card">
  <h2><a href="p/{esc(p['slug'])}.html">{esc(p['title'])}</a></h2>
  <p class="meta">{esc(p['date'])} · <a href="{esc(p['repo_url'])}">{esc(p['repo'])}</a> · ★ {p.get('stars', '?')} · {esc(p.get('language', ''))}</p>
  <p>{esc(p['summary'])}</p>
</article>""")
    content = "\n".join(cards) if cards else "<p>First post coming soon.</p>"
    return PAGE.format(title=SITE_NAME, description=TAGLINE, base="",
                       site=SITE_NAME, tagline=TAGLINE, content=content,
                       cssv=css_version())


def render_post(p):
    explainer = ""
    if p.get("explainer_url"):
        # Scrimba's player can't boot inside a cross-origin iframe (its session
        # WebSocket fails under third-party storage partitioning), so we render
        # a click-through player card instead of an embed.
        url = esc(p["explainer_url"])
        explainer = f"""<a class="explainer-card" href="{url}" target="_blank" rel="noopener">
  <span class="play">▶</span>
  <span class="explainer-text">
    <strong>Watch the interactive explainer</strong>
    <span>Narrated visual walkthrough of {esc(p['repo'])} · free on Scrimba</span>
  </span>
</a>"""
    content = f"""<article>
<h1>{esc(p['title'])}</h1>
<p class="meta">{esc(p['date'])} · <a href="{esc(p['repo_url'])}">{esc(p['repo'])}</a> · ★ {p.get('stars', '?')}</p>
{explainer}
{p['body_html']}
</article>
<p><a href="../index.html">← All posts</a></p>"""
    return PAGE.format(title=f"{p['title']} — {SITE_NAME}",
                       description=p["summary"][:150], base="../",
                       site=SITE_NAME, tagline=TAGLINE, content=content,
                       cssv=css_version())


def main():
    os.makedirs(os.path.join(DOCS, "p"), exist_ok=True)
    posts = load_posts()
    with open(os.path.join(DOCS, "index.html"), "w") as f:
        f.write(render_index(posts))
    for p in posts:
        with open(os.path.join(DOCS, "p", p["slug"] + ".html"), "w") as f:
            f.write(render_post(p))
    print(f"built site: {len(posts)} post(s)")


if __name__ == "__main__":
    main()
