#!/usr/bin/env python3
"""Assemble the static site in docs/ from post JSON files in data/posts/.

Each post file: { slug, title, repo, repo_url, date, summary, explainer_url,
body_html, stars, language }
body_html is trusted (generated by our own pipeline).
"""
import glob
import hashlib
import html
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DOCS = os.path.join(ROOT, "docs")
SITE_NAME = "Repo, Explained"
TAGLINE = "One trending GitHub repo, explained visually. Every day. Fully automated."
SITE_URL = "https://ibrhmvk.github.io/trending-explained"

PAGE = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title}</title>
<meta name="description" content="{description}">
{meta}
<link rel="alternate" type="application/rss+xml" title="{site}" href="{base}feed.xml">
<link rel="stylesheet" href="{base}style.css?v={cssv}">
<link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>📦</text></svg>">
</head>
<body class="{bodyclass}">
<header>
  <a class="brand" href="{base}index.html">📦 {site}</a>
  <p class="tagline">{tagline}</p>
</header>
<main>
{content}
</main>
<footer>
  <!-- AD SLOT: paste your EthicalAds / Carbon snippet here -->
  <p>Generated automatically with Claude Code + Scrimba Explain.</p>
</footer>
</body>
</html>
"""


def load_posts():
    posts = []
    for path in glob.glob(os.path.join(ROOT, "data", "posts", "*.json")):
        with open(path) as f:
            posts.append(json.load(f))
    posts.sort(key=lambda p: p["date"], reverse=True)
    return posts


def esc(s):
    return html.escape(s or "", quote=True)


def css_version():
    with open(os.path.join(DOCS, "style.css"), "rb") as f:
        return hashlib.sha1(f.read()).hexdigest()[:8]


def og_meta(title, description, url, article=None):
    tags = [
        f'<meta property="og:title" content="{esc(title)}">',
        f'<meta property="og:description" content="{esc(description)}">',
        f'<meta property="og:url" content="{esc(url)}">',
        f'<meta property="og:site_name" content="{esc(SITE_NAME)}">',
        f'<meta property="og:type" content="{"article" if article else "website"}">',
        '<meta name="twitter:card" content="summary">',
    ]
    if article:
        tags.append(f'<meta property="article:published_time" content="{esc(article["date"])}">')
        ld = {"@context": "https://schema.org", "@type": "TechArticle",
              "headline": article["title"], "description": article["summary"],
              "datePublished": article["date"], "url": url,
              "about": article["repo"], "publisher": {"@type": "Organization",
                                                      "name": SITE_NAME}}
        tags.append('<script type="application/ld+json">'
                    + json.dumps(ld) + "</script>")
    return "\n".join(tags)


def pills(p, link_repo=True):
    lang = (f'<span class="pill"><span class="dot"></span>{esc(p["language"])}</span>'
            if p.get("language") else "")
    repo = (f'<a class="pill" href="{esc(p["repo_url"])}" target="_blank" rel="noopener">{esc(p["repo"])} ↗</a>'
            if link_repo else "")
    stars = p.get("stars")
    stars = f"{stars:,}" if isinstance(stars, int) else "?"
    return (f'<div class="pills"><span class="pill">{esc(p["date"])}</span>'
            f'<span class="pill">★ {stars}</span>{lang}{repo}</div>')


def render_index(posts):
    cards = []
    for p in posts:
        cards.append(f"""<article class="card">
  <h2><a href="p/{esc(p['slug'])}.html">{esc(p['title'])}</a></h2>
  <p class="summary">{esc(p['summary'])}</p>
  {pills(p)}
</article>""")
    content = ('<div class="cards">\n' + "\n".join(cards) + "\n</div>"
               if cards else "<p>First post coming soon.</p>")
    return PAGE.format(title=SITE_NAME, description=TAGLINE, base="",
                       site=SITE_NAME, tagline=TAGLINE, content=content,
                       cssv=css_version(), bodyclass="home",
                       meta=og_meta(SITE_NAME, TAGLINE, SITE_URL + "/"))


def render_post(p):
    explainer = ""
    if p.get("explainer_url"):
        url = esc(p["explainer_url"])
        explainer = f"""<div class="explainer-embed">
  <iframe src="{url}" loading="lazy" allowfullscreen
          title="Interactive explainer for {esc(p['repo'])}"></iframe>
  <div class="controls-cover" aria-hidden="true"></div>
</div>
<p class="explainer-fallback"><a href="{url}" target="_blank" rel="noopener">Player not loading? Open the explainer on Scrimba ↗</a></p>"""
    content = f"""<article>
<h1>{esc(p['title'])}</h1>
{pills(p)}
{explainer}
{p['body_html']}
</article>
<a class="back" href="../index.html">← All posts</a>"""
    url = f"{SITE_URL}/p/{p['slug']}.html"
    return PAGE.format(title=f"{p['title']} — {SITE_NAME}",
                       description=p["summary"][:150], base="../",
                       site=SITE_NAME, tagline=TAGLINE, content=content,
                       cssv=css_version(), bodyclass="",
                       meta=og_meta(p["title"], p["summary"], url, article=p))


def render_sitemap(posts):
    urls = [f"<url><loc>{SITE_URL}/</loc></url>"]
    urls += [f"<url><loc>{SITE_URL}/p/{esc(p['slug'])}.html</loc>"
             f"<lastmod>{esc(p['date'])}</lastmod></url>" for p in posts]
    return ('<?xml version="1.0" encoding="UTF-8"?>\n'
            '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
            + "\n".join(urls) + "\n</urlset>\n")


def render_rss(posts):
    from datetime import datetime, timezone
    from email.utils import format_datetime
    items = []
    for p in posts[:30]:
        pub = format_datetime(datetime.fromisoformat(p["date"])
                              .replace(hour=9, minute=30, tzinfo=timezone.utc))
        url = f"{SITE_URL}/p/{p['slug']}.html"
        items.append(f"""<item>
<title>{esc(p['title'])}</title>
<link>{url}</link>
<guid isPermaLink="true">{url}</guid>
<pubDate>{pub}</pubDate>
<description>{esc(p['summary'])}</description>
</item>""")
    return f"""<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0"><channel>
<title>{esc(SITE_NAME)}</title>
<link>{SITE_URL}/</link>
<description>{esc(TAGLINE)}</description>
{chr(10).join(items)}
</channel></rss>
"""


def main():
    os.makedirs(os.path.join(DOCS, "p"), exist_ok=True)
    posts = load_posts()
    with open(os.path.join(DOCS, "index.html"), "w") as f:
        f.write(render_index(posts))
    for p in posts:
        with open(os.path.join(DOCS, "p", p["slug"] + ".html"), "w") as f:
            f.write(render_post(p))
    with open(os.path.join(DOCS, "sitemap.xml"), "w") as f:
        f.write(render_sitemap(posts))
    with open(os.path.join(DOCS, "feed.xml"), "w") as f:
        f.write(render_rss(posts))
    with open(os.path.join(DOCS, "robots.txt"), "w") as f:
        f.write(f"User-agent: *\nAllow: /\nSitemap: {SITE_URL}/sitemap.xml\n")
    print(f"built site: {len(posts)} post(s)")


if __name__ == "__main__":
    main()
